### ISSUE TITLE
Recuo de título de um capítulo

### ISSUE THREAD

**Issue by brunolnetto** [lfochamon/poliTeX#3]
Existe alguém que presta manutenção a este repositório? Eu gostaria de modificar o estilo de poliTeX para poder adicionar um recuo negativo ao espaçamento acima do título de cada capítulo. Eu estou com dificuldade de realizar esta tarefa. Alguém de vocês pode me ajudar com esta tarefa?

**Comment by lfochamon** [comment]
Deixa eu entender direito o que voce esta tentando fazer. Voce gostaria de diminuir o espacamento entre o topo da pagina e o titulo do capitulo?

Voce pode trocar isso modificando a [linha 581](https://github.com/lfochamon/poliTeX/blob/d68bbb336da6ce18ee1ad1da40f35866a9f1f6fe/politex.cls#L581) do `politex.cls`. O padrao e' 30pt, voce pode substituir por 15pt, 6pt ou comentar a linha se nao quiser nenhum espaco.

(eu nao testei essa solucao, me avisa se nao funcionar)

**Comment by brunolnetto** [comment]
Mais precisamente, eu gostaria de diminuir o espaço entre a linha horizontal do número da página e a primeira linha do título.

**Comment by lfochamon** [comment]
Cool... O que eu sugeri nao funcionou?

> Voce pode trocar isso modificando a [linha 581](https://github.com/lfochamon/poliTeX/blob/d68bbb336da6ce18ee1ad1da40f35866a9f1f6fe/politex.cls#L581) do `politex.cls`. O padrao e' 30pt, voce pode substituir por 15pt, 6pt ou comentar a linha se nao quiser nenhum espaco.

**Comment by brunolnetto** [comment]
Eu mudei para 0pt e não aconteceu nada. ;/

**Comment by brunolnetto** [comment]
Ah, eu não disse que é o apêndice! 

\apendice

**Comment by lfochamon** [comment]
Eu testei aqui e e' isso mesmo. Aconteceu sim, so nao o suficiente. E' que `\vspace*{0pt}` nao e' o mesmo que nao por espaco porque... porque latex :P

Comente ou use `\vspace*{-30pt}` (ou algum outro valor mais negativo).

**Comment by lfochamon** [comment]
Pois e' importante dizer isso mesmo! Hahahahaha

Para o apendice edita a [linha 741](https://github.com/lfochamon/poliTeX/blob/d68bbb336da6ce18ee1ad1da40f35866a9f1f6fe/politex.cls#L741)

**Comment by brunolnetto** [comment]
Perfeito, obrigado.
