### ISSUE TITLE
Referências

### ISSUE THREAD

**Issue by kogake** [lfochamon/poliTeX#5]
Lista de problemas com as referências:
1 - O site https://ctan.org/tex-archive/macros/latex/contrib/abntex2/tex, quando você clica no download do zip, não está baixando nada, tentei ontem e hoje e não consegui. 

Caso possível, fazer uma explicação melhor sobre essa parte de referências, instalação e utilização

**Comment by lfochamon** [comment]
Eu acabo de entrar no site seguindo o link do `README` e consegui baixar o `zip` sem problemas.

Infelizmente, eu nao tenho tempo para ajudar com problemas relativos ao `CTAN` (repositorio de pacotes do latex) ou `bibtex`. Voce tem razao que o `README` so explica por cima o que fazer com as referencias, mas e' porque isso nao tem nada a ver com o poliTeX. E' um processo separado.

Tenho certeza que com um pouco de google voce consegue descobrir. Mas e' verdade que LaTeX nem sempre e' simples...
