### ISSUE TITLE
Sumário e string de título

### ISSUE THREAD

**Issue by brunolnetto** [lfochamon/poliTeX#6]
Como eu altero a string "Contents", em inglês no sumário?

**Comment by lfochamon** [comment]
Como aparece no pdf de exemplo, o sumario tem tag "Sumario" e nao "Contents."

Ja nao mantenho esse pacote ativamente, entao realmente so corrijo problemas. Por isso, ja nao tiro duvidas nas issues.

**Comment by brunolnetto** [comment]
Ao mudar o idioma para "english" no pacote "babel", "Sumário" torna-se "Contents". Eu gostaria de converter para algo personalizável.
