### ISSUE TITLE
Seção "Nomenclatura" não compila como saída

### ISSUE THREAD

**Issue by brunolnetto** [lfochamon/poliTeX#7]
Olá. Eu uso esta biblioteca como template para meu mestrado. Durante seu uso, eu utilizo biblioteca `nomencl` para criar uma seção com símbolos e conveções matemáticas. Como você pode testar abaixo, o cabeçalho `\documentclass{article}`compila, enquanto o cabeçalho `\documentclass[twosideprint, abnttoc, espacosimples]{politex}` não compila. 

https://www.overleaf.com/4276873953hgghbvwfdxdh

Eu tenho este problema frequentemente e gostaria de ter uma seção nomenclatura em minha tese. Você pode me ajudar?

**Comment by lfochamon** [comment]
Eu nao uso overleaf, então só posso entrar acessar link que é `read-only`. Pelo visto, o `nomencl` tem algumas incompatibilidades com pacote que mexem na formatação da TOC. Você pode tentar tirar a opção `abnttoc` e/ou usar a opção `notocbasic` no `nomencl`. Mas sem ver o erro fica difícil saber qual a origem do problema.

Infelizmente, não tenho muito tempo pra me aprofundar no que poderia ser. Se descobrir me avisa e a gente tenta consertar.

**Comment by brunolnetto** [comment]
A minha tentativa em consertar este problema foi: 

1. baixar o projeto;
2. compular em ambiente Unix tanto com cabeçalho `\documentclass{article}` quanto `\documentclass{politex}`. 

```
pdflatex main.tex
makeindex main.nlo -s nomencl.ist -o main.nls
pdflatex main.tex
```

Existe probabilidade não-nula, mas baixa, de eu resolver este problema sozinho.

**Comment by lfochamon** [comment]
Por favor enviar o error. Sem ver o erro, nao tenho como te ajudar.

**Comment by brunolnetto** [comment]
É um erro silencioso: ele não compila a nomenclatura e insere no pdf. Frustrante

**Comment by lfochamon** [comment]
Infelizmente, se nao tem error, nao posso te ajudar. Deve ser uma incompatibilidade do `nomencl`, dessas que tipicas do `LaTeX`. Como nunca usei esse pacote, nao posso te ajudar alem das dicas que ja te dei.

Procure sempre compilar mais de uma vez depois de atualizar os arquivos auxiliares, como para o `bibtex`.

**Comment by brunolnetto** [comment]
Claro que consegue me ajudar: você pode ver se tem uma cadeira vaga aí do seu lado em Stuttgart.

**Comment by lfochamon** [comment]
https://luizchamon.com/pages/prospective-members.html

Fica a dica! :wink:

**Comment by brunolnetto** [comment]
1. Pergunta: Qual ferramenta você usou para seu site?
2. Apresentação: Eu tenho este artigo publicado no SBAI. Eu peço e veja se ele contribui para sua pesquisa. Eu posso encaminhar minha Master Thesis se você quiser.

https://www.sba.org.br/open_journal_systems/index.php/sbai/article/view/2631 

3. Qual o valor do Stipendium para PhD em Stuttgart?
Editted: Eu achei aqui: https://luizchamon.com/pages/prospective-members.html#so-whats-the-salary-exactly

PS.: Minha tese é uma alternativa para este artigo seu com B. Angélico: https://arxiv.org/abs/1909.07496

**Comment by brunolnetto** [comment]
Para seguirmos modelo orientador-orientando, segue minhas percepções: A classe  `politex` apresenta macro-sessões abaixo. Você pode listar as seções que você acha relevantes que eu deva experimentar com uma lista, por exemplo, `[1, 2]` ou `[2]` ou definir subitem em formato _array_, `[1.a, 1.b, 1.d, 2.b]` 

1. PREAMBLE
    a. IDENTIFICATION;
    b. REQUIRED PACKAGES;
    c. INTERNATIONALIZATION;
    d. OPTIONS DECLARATIONS;
    e. LOAD REPORT CLASS;
2. IMPLEMENTATION
    a. PAGE SETTINGS AND PACKAGES;
    b. HEADER STYLE;
    c. MARGIN SETTINGS;
    d. PAGE NUMBERING;
    e. LINE SPACING
    f. PART/CHAPTER/SECTION STYLE
    g. ANNEX AND APPENDIX
    h. TOC
    i. LIST OF TABLES
    k. BIBLIOGRAPHY
    l. INDEX
3. PRE-TEXTUAL ELEMENTS
    a. FRONT PAGE
    b. TITLE PAGE
    c. COMMENTS (DOCUMENT TYPE)
    d. DEDICATION
    e. ACKNOWLEDGEMENTS
    f. EPIGRAPH
    g. ABSTRACT
    h. RESUMO
    i. SIGNATURE SHEET
    k. TIMES FONT
    j. ARBITRARY PRE TEXTUAL SECTION
    l. POST SECTION INDENTATION

**Comment by brunolnetto** [comment]
Eu gerei um projeto exemplo só com nomenclatura e funcionou: https://www.overleaf.com/4276873953hgghbvwfdxdh
Estranho. Deve ser alguma configuração conflitante.

**Comment by brunolnetto** [comment]
Eu consigo gerar a seção de nomenclatura ao criar um projeto limpo e usar `politex` ao invés de `article`. Comportamento estranho: se eu volto `politex` para `article`, o documento não gera nomenclatura.

```
\documentclass{article}

\usepackage{nomencl}
\makenomenclature

\begin{document}
    
    \nomenclature{\(c\)}{Speed of light in a vacuum}
    \nomenclature{\(h\)}{Planck constant}
    \printnomenclature

\end{document}
```

**Comment by brunolnetto** [comment]
EUREKA!

Remover linhas 251 a 274 do arquivo politex.cls gera a nomenclatura. A próxima pergunta é: por quê?

**Comment by brunolnetto** [comment]
Resposta: https://tex.stackexchange.com/questions/668341/nomenclature-generation-fails-on-custom-template-class/668352#668352

**Comment by lfochamon** [comment]
@brunolnetto Entao o problema é do `nomencl` mesmo :P Confirma se tudo funciona removendo só a linha [255](https://github.com/lfochamon/poliTeX/blob/b0454c43d2e05f13b12da4ac556fc8f7f6ae6361/politex.cls#L255) e se for o caso, faz um pull request que eu incorporo a solucao.

**Comment by brunolnetto** [comment]
Eu mandei o PR e outro refatorando o README. A ideia principal é mover a seção `Uso` para aba `Wiki`. 

Outra ideia que eu tenho, que requer algum nível de engajamento da comunidade, é converter `poliTeX` em `TeXtual`, com suporte para várias línguas. O que acha?

**Comment by lfochamon** [comment]
Essa e uma questao diferente, nao vamos poluir essa issue que ja fechou com o seu PR.

Mas eu nao atualizo esse pacote mais. So bugs. Nao estou na POLI, ja nao e meu problema. Mas se ha demanda, fique a vontade para criar um fork e seguir em frente com o desenvolvimento.

**Comment by brunolnetto** [comment]
Existe demanda sempre que existe usuário. E é uma atitude louvável se você dá manutenção em algo que você compreende.
